#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: Super Cypher

# Short bio or description (displayed in the header)
description: Fabulous Things

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar:

#
# Flags below are optional
#

# Your website URL (e.g. https://forever-jekyll.github.io or https://forever-jekyll.com)
# Used for Sitemap.xml and your RSS feed
url: http://nibl.github.io

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

# Navigation menu
navigation_links:
  - title: Home
    url: /

  - title: Search
    url: /search
    
  - title: About
    url: /about

  - title: Contact
    url: /contact
    
  - title: Movies
    url: /movies.html
    
# Collections

collections:
    movies:
     output: true
    
    # avengers  
    a:
     # output: true
     
    # bond   
    b:
     output: true
    
    # fun
    f:
     output: true
    
    # interviews
    i:
     output: true
     
    # lists
    l:
     output: true
      
    # suggestions, spoiler-light
    s:
     output: true
    
    # reviews
    r:
     output: true
      
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "movies"
    values:
        layout: "movie"
  - scope:
      path: ""
    values:
        layout: "default"

# Footer icons
footer_links:
  - title: Feed
    url: feed.xml
    icon: fa fa-rss-square

  - title: GitHub
    url: https://github.com/nibl
    icon: fa fa-github-square

# Enter your copyright text if you wish to override the default one.
#copyright: "This site is made with <3 by *me, myself, and I*."

#
# !! You don't need to change any of the configuration flags below !!
#

permalink: /:slug

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Pagination
paginate: 10
paginate_path: "/page/:num/"

# Set the Sass partials directory, as we're using @imports
sass:
  sass_dir: _sass
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jemoji

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME